# Generated by Django 5.2.3 on 2025-06-16 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('nutritional_archetype', models.CharField(choices=[('FIT', 'Perfil Fitness'), ('ANC', 'Guerrero Ancestral'), ('DRU', 'Druida del Equilibrio')], max_length=3)),
                ('physical_archetype', models.CharField(choices=[('CAL', 'Calistenia'), ('GYM', 'Berserker de Gimnasio'), ('FLX', 'Monje de la Flexibilidad'), ('RUN', 'Corredor del Viento')], max_length=3)),
                ('spiritual_path', models.CharField(choices=[('ZEN', 'Budista Zen'), ('CHR', 'Cristiano Comprometido'), ('STO', 'Filósofo Estoico')], max_length=3)),
                ('login_streak', models.IntegerField(default=0)),
                ('spiritual_streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_value', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.quest')),
            ],
            options={
                'unique_together': {('character', 'quest', 'completion_date')},
            },
        ),
    ]
