# Generated by Django 5.2.3 on 2025-06-29 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='spiritual_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='xp_to_next_level',
        ),
        migrations.AlterField(
            model_name='nutritionalarchetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalarchetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='nutritional_archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_core.nutritionalarchetype'),
        ),
        migrations.AlterField(
            model_name='player',
            name='physical_archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_core.physicalarchetype'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spiritual_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legacy_core.spiritualpath'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spiritualpath',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
