# Generated by Django 5.2.3 on 2025-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_questtype_rename_title_quest_name_quest_quest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='time_of_day',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], default='Morning', max_length=10),
        ),
    ]
